### PR TITLE
Enable windows support

### PR DESCRIPTION
**Pull request by Hofer-Julian**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
@conda-forge-admin, please rerender

**Comment by Hofer-Julian** [comment]
@conda-forge-admin, please rerender

**Comment by mwtoews** [comment]
By default, flang is used on Windows ([this source](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/conda_build_config.yaml)), which isn't supported for mf6 (yet?).

A suggested edit is:
```diff

diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index 50929f3..71a9047 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -15,6 +15,7 @@ build:
 requirements:
   build:
     - {{ compiler('fortran') }}
+    - {{ compiler('m2w64_fortran') }}  # [win]
     - meson
     - ninja
```
which should ideally choose GCC Fortran (MinGW-w64), which works fine with mf6.

**Comment by Hofer-Julian** [comment]
@conda-forge-admin, please rerender

**Comment by mwtoews** [comment]
rollback 075c08894fcb6b4679da3d9b1a3c8717e875873e since the compiler is not always "gfortran", particularly when cross-compiling etc. The linux failure is because the compiler is "x86_64-conda-linux-gnu-gfortran".

**Comment by Hofer-Julian** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
